- name: Install build-essentails to make
  apt: name=build-essential

- name: Extracting redis package
  unarchive: src="{{ installers_base_url }}/redis-3.2.3.tar.gz" dest=/opt/ remote_src=yes

- name: Install redis
  make:
    chdir: /opt/redis-3.2.3/
    target: install
  become: yes

- name: install redis as service
  become: yes
  shell: echo | /opt/redis-3.2.3/utils/install_server.sh creates=/var/lib/redis/6379

- name: Copy Redis configuration
  template: src=redis.conf.j2 dest=/opt/redis-3.2.3/redis.conf

- name: Ensure redis is started and runs on startup.
  service: name=redis_6379 state=started enabled=yes
