cluster.name: {{ internal_domain }}-elasticsearch
node.name: ${HOSTNAME}
discovery.zen.ping.unicast.hosts: ["master-1-elasticsearch.{{ internal_domain }}" , "master-2-elasticsearch.{{ internal_domain }}" , "master-3-elasticsearch.{{ internal_domain }}" , "data-1-elasticsearch.{{ internal_domain }}" , "data-2-elasticsearch.{{ internal_domain }}" ]
node.master: false 
node.data: true
network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 2
bootstrap.memory_lock: true
path.data: /data/elasticsearch