---

- name: Add curator repository
  apt_repository: repo='deb [arch=amd64] http://packages.elastic.co/curator/5/debian stable main' state=present

- name: Install package curator
  apt: name=elasticsearch-curator state=present update_cache=yes

 
- name: Remove old curator crontab
  file: path=/etc/cron.d/{{ item }} state=absent
  tags: cron
  with_items:
    - 'curator'
    - 'curator_clean'
    - 'curator_close'
    - 'curator_delete'
 
- name: Adding curator delete crontab
  cron: name='curator_delete'
        minute='0' hour='10'
        user='root'
        job='/usr/bin/curator --host {{ elasticsearch.ip }} delete indices --time-unit days --timestring "\%Y.\%m.\%d" --older-than {{ curator_max_keep_days | default(360) }}'
        cron_file='curator_delete'
        state='present'
  tags: cron
 
- name: Adding curator close crontab
  cron: name='curator_close'
        minute='45' hour='9'
        user='root'
        job='/usr/bin/curator --host {{ elasticsearch.ip }} close indices --time-unit days --timestring "\%Y.\%m.\%d" --older-than {{ curator_close_after_days | default(14) }}'
        cron_file='curator_close'
        state='present'
  tags: cron
