- name: "Installing 7zip"
  apt: >
    name={{ item }}
    state=present
  with_items:
    - p7zip-full

- name: Changing filesystem to ext4
  filesystem:
    fstype: ext4
    dev: /dev/xvdc

- name: Create mountable dir
  file: path="/home/mettl/disha/cetificates" state=directory mode="755" owner=mettl group=mettl

- name: set mountpoints
  mount: name=/home/mettl/disha/cetificates src=/dev/xvdc fstype=ext4 opts=defaults,nofail,comment=cloudconfig dump=0 passno=0 state=present
