dependencies:
  - { role: base-nfs-client, when: (is_nfs_itself is not defined) or (is_nfs_itself == false)}
  - { role: filebeat, when: install_filebeat == true}
  #- { role: zabbix-agent, when: install_zabbix_agent == true}
  - { role: awscli}
  - { role: ntp}
  - { role: instance-monitoring}
